/*
 * XI Sdk Resellers
 *
 * For resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of APIs and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing AsyncOrderCreateDTOWarrantyInfoInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AsyncOrderCreateDTOWarrantyInfoInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AsyncOrderCreateDTOWarrantyInfoInner
        //private AsyncOrderCreateDTOWarrantyInfoInner instance;

        public AsyncOrderCreateDTOWarrantyInfoInnerTests()
        {
            // TODO uncomment below to create an instance of AsyncOrderCreateDTOWarrantyInfoInner
            //instance = new AsyncOrderCreateDTOWarrantyInfoInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AsyncOrderCreateDTOWarrantyInfoInner
        /// </summary>
        [Fact]
        public void AsyncOrderCreateDTOWarrantyInfoInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" AsyncOrderCreateDTOWarrantyInfoInner
            //Assert.IsType<AsyncOrderCreateDTOWarrantyInfoInner>(instance);
        }

        /// <summary>
        /// Test the property 'HardwareLineLink'
        /// </summary>
        [Fact]
        public void HardwareLineLinkTest()
        {
            // TODO unit test for the property 'HardwareLineLink'
        }

        /// <summary>
        /// Test the property 'WarrantyLineLink'
        /// </summary>
        [Fact]
        public void WarrantyLineLinkTest()
        {
            // TODO unit test for the property 'WarrantyLineLink'
        }

        /// <summary>
        /// Test the property 'DirectLineLink'
        /// </summary>
        [Fact]
        public void DirectLineLinkTest()
        {
            // TODO unit test for the property 'DirectLineLink'
        }

        /// <summary>
        /// Test the property 'SerialInfo'
        /// </summary>
        [Fact]
        public void SerialInfoTest()
        {
            // TODO unit test for the property 'SerialInfo'
        }

        /// <summary>
        /// Test the property 'VmfAdditionalAttributesLines'
        /// </summary>
        [Fact]
        public void VmfAdditionalAttributesLinesTest()
        {
            // TODO unit test for the property 'VmfAdditionalAttributesLines'
        }
    }
}
