/*
 * XI Sdk Resellers
 *
 * For resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing AsyncOrderCreateResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AsyncOrderCreateResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AsyncOrderCreateResponse
        //private AsyncOrderCreateResponse instance;

        public AsyncOrderCreateResponseTests()
        {
            // TODO uncomment below to create an instance of AsyncOrderCreateResponse
            //instance = new AsyncOrderCreateResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AsyncOrderCreateResponse
        /// </summary>
        [Fact]
        public void AsyncOrderCreateResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AsyncOrderCreateResponse
            //Assert.IsType<AsyncOrderCreateResponse>(instance);
        }

        /// <summary>
        /// Test the property 'QuoteNumber'
        /// </summary>
        [Fact]
        public void QuoteNumberTest()
        {
            // TODO unit test for the property 'QuoteNumber'
        }

        /// <summary>
        /// Test the property 'ConfirmationNumber'
        /// </summary>
        [Fact]
        public void ConfirmationNumberTest()
        {
            // TODO unit test for the property 'ConfirmationNumber'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
