/*
 * XI Sdk Resellers
 *
 * For resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of APIs and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner
        //private AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner instance;

        public AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInnerTests()
        {
            // TODO uncomment below to create an instance of AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner
            //instance = new AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner
        /// </summary>
        [Fact]
        public void AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner
            //Assert.IsType<AsyncOrderCreateDTOWarrantyInfoInnerSerialInfoInner>(instance);
        }

        /// <summary>
        /// Test the property 'DateOfPurchase'
        /// </summary>
        [Fact]
        public void DateOfPurchaseTest()
        {
            // TODO unit test for the property 'DateOfPurchase'
        }

        /// <summary>
        /// Test the property 'ShipDate'
        /// </summary>
        [Fact]
        public void ShipDateTest()
        {
            // TODO unit test for the property 'ShipDate'
        }

        /// <summary>
        /// Test the property 'PrimarySerialNumber'
        /// </summary>
        [Fact]
        public void PrimarySerialNumberTest()
        {
            // TODO unit test for the property 'PrimarySerialNumber'
        }

        /// <summary>
        /// Test the property 'SecondarySerialNumber'
        /// </summary>
        [Fact]
        public void SecondarySerialNumberTest()
        {
            // TODO unit test for the property 'SecondarySerialNumber'
        }
    }
}
