/*
 * XI Sdk Resellers
 *
 * For resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of APIs and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing AsyncOrderCreateDTOLinesInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AsyncOrderCreateDTOLinesInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AsyncOrderCreateDTOLinesInner
        //private AsyncOrderCreateDTOLinesInner instance;

        public AsyncOrderCreateDTOLinesInnerTests()
        {
            // TODO uncomment below to create an instance of AsyncOrderCreateDTOLinesInner
            //instance = new AsyncOrderCreateDTOLinesInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AsyncOrderCreateDTOLinesInner
        /// </summary>
        [Fact]
        public void AsyncOrderCreateDTOLinesInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" AsyncOrderCreateDTOLinesInner
            //Assert.IsType<AsyncOrderCreateDTOLinesInner>(instance);
        }

        /// <summary>
        /// Test the property 'CustomerLineNumber'
        /// </summary>
        [Fact]
        public void CustomerLineNumberTest()
        {
            // TODO unit test for the property 'CustomerLineNumber'
        }

        /// <summary>
        /// Test the property 'IngramPartNumber'
        /// </summary>
        [Fact]
        public void IngramPartNumberTest()
        {
            // TODO unit test for the property 'IngramPartNumber'
        }

        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }

        /// <summary>
        /// Test the property 'UnitPrice'
        /// </summary>
        [Fact]
        public void UnitPriceTest()
        {
            // TODO unit test for the property 'UnitPrice'
        }

        /// <summary>
        /// Test the property 'SpecialBidNumber'
        /// </summary>
        [Fact]
        public void SpecialBidNumberTest()
        {
            // TODO unit test for the property 'SpecialBidNumber'
        }

        /// <summary>
        /// Test the property 'EndUserPrice'
        /// </summary>
        [Fact]
        public void EndUserPriceTest()
        {
            // TODO unit test for the property 'EndUserPrice'
        }

        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Fact]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }

        /// <summary>
        /// Test the property 'EndUserInfo'
        /// </summary>
        [Fact]
        public void EndUserInfoTest()
        {
            // TODO unit test for the property 'EndUserInfo'
        }
    }
}
