/*
 * XI Sdk Resellers
 *
 * For Resellers. Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing InvoiceDetailResponseServiceresponseInvoicedetailresponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InvoiceDetailResponseServiceresponseInvoicedetailresponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InvoiceDetailResponseServiceresponseInvoicedetailresponse
        //private InvoiceDetailResponseServiceresponseInvoicedetailresponse instance;

        public InvoiceDetailResponseServiceresponseInvoicedetailresponseTests()
        {
            // TODO uncomment below to create an instance of InvoiceDetailResponseServiceresponseInvoicedetailresponse
            //instance = new InvoiceDetailResponseServiceresponseInvoicedetailresponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InvoiceDetailResponseServiceresponseInvoicedetailresponse
        /// </summary>
        [Fact]
        public void InvoiceDetailResponseServiceresponseInvoicedetailresponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" InvoiceDetailResponseServiceresponseInvoicedetailresponse
            //Assert.IsType<InvoiceDetailResponseServiceresponseInvoicedetailresponse>(instance);
        }

        /// <summary>
        /// Test the property 'Customernumber'
        /// </summary>
        [Fact]
        public void CustomernumberTest()
        {
            // TODO unit test for the property 'Customernumber'
        }

        /// <summary>
        /// Test the property 'Invoicenumber'
        /// </summary>
        [Fact]
        public void InvoicenumberTest()
        {
            // TODO unit test for the property 'Invoicenumber'
        }

        /// <summary>
        /// Test the property 'Invoicedate'
        /// </summary>
        [Fact]
        public void InvoicedateTest()
        {
            // TODO unit test for the property 'Invoicedate'
        }

        /// <summary>
        /// Test the property 'Invoicetype'
        /// </summary>
        [Fact]
        public void InvoicetypeTest()
        {
            // TODO unit test for the property 'Invoicetype'
        }

        /// <summary>
        /// Test the property 'Customerordernumber'
        /// </summary>
        [Fact]
        public void CustomerordernumberTest()
        {
            // TODO unit test for the property 'Customerordernumber'
        }

        /// <summary>
        /// Test the property 'Customerfreightamount'
        /// </summary>
        [Fact]
        public void CustomerfreightamountTest()
        {
            // TODO unit test for the property 'Customerfreightamount'
        }

        /// <summary>
        /// Test the property 'Customerforeignfrightamt'
        /// </summary>
        [Fact]
        public void CustomerforeignfrightamtTest()
        {
            // TODO unit test for the property 'Customerforeignfrightamt'
        }

        /// <summary>
        /// Test the property 'Totaltaxamount'
        /// </summary>
        [Fact]
        public void TotaltaxamountTest()
        {
            // TODO unit test for the property 'Totaltaxamount'
        }

        /// <summary>
        /// Test the property 'Totalamount'
        /// </summary>
        [Fact]
        public void TotalamountTest()
        {
            // TODO unit test for the property 'Totalamount'
        }

        /// <summary>
        /// Test the property 'Shiptosuffix'
        /// </summary>
        [Fact]
        public void ShiptosuffixTest()
        {
            // TODO unit test for the property 'Shiptosuffix'
        }

        /// <summary>
        /// Test the property 'Billtosuffix'
        /// </summary>
        [Fact]
        public void BilltosuffixTest()
        {
            // TODO unit test for the property 'Billtosuffix'
        }

        /// <summary>
        /// Test the property 'Freightamount'
        /// </summary>
        [Fact]
        public void FreightamountTest()
        {
            // TODO unit test for the property 'Freightamount'
        }

        /// <summary>
        /// Test the property 'Paymentterms'
        /// </summary>
        [Fact]
        public void PaymenttermsTest()
        {
            // TODO unit test for the property 'Paymentterms'
        }

        /// <summary>
        /// Test the property 'Orderdate'
        /// </summary>
        [Fact]
        public void OrderdateTest()
        {
            // TODO unit test for the property 'Orderdate'
        }

        /// <summary>
        /// Test the property 'Carrier'
        /// </summary>
        [Fact]
        public void CarrierTest()
        {
            // TODO unit test for the property 'Carrier'
        }

        /// <summary>
        /// Test the property 'Carrierdescription'
        /// </summary>
        [Fact]
        public void CarrierdescriptionTest()
        {
            // TODO unit test for the property 'Carrierdescription'
        }

        /// <summary>
        /// Test the property 'Discountamount'
        /// </summary>
        [Fact]
        public void DiscountamountTest()
        {
            // TODO unit test for the property 'Discountamount'
        }

        /// <summary>
        /// Test the property 'Taxtype'
        /// </summary>
        [Fact]
        public void TaxtypeTest()
        {
            // TODO unit test for the property 'Taxtype'
        }

        /// <summary>
        /// Test the property 'Enduserponumber'
        /// </summary>
        [Fact]
        public void EnduserponumberTest()
        {
            // TODO unit test for the property 'Enduserponumber'
        }

        /// <summary>
        /// Test the property 'Freightforwardercode'
        /// </summary>
        [Fact]
        public void FreightforwardercodeTest()
        {
            // TODO unit test for the property 'Freightforwardercode'
        }

        /// <summary>
        /// Test the property 'Creditmemoreasoncode'
        /// </summary>
        [Fact]
        public void CreditmemoreasoncodeTest()
        {
            // TODO unit test for the property 'Creditmemoreasoncode'
        }

        /// <summary>
        /// Test the property 'Fulfillmentflag'
        /// </summary>
        [Fact]
        public void FulfillmentflagTest()
        {
            // TODO unit test for the property 'Fulfillmentflag'
        }

        /// <summary>
        /// Test the property 'Holdreason'
        /// </summary>
        [Fact]
        public void HoldreasonTest()
        {
            // TODO unit test for the property 'Holdreason'
        }

        /// <summary>
        /// Test the property 'Shipcomplete'
        /// </summary>
        [Fact]
        public void ShipcompleteTest()
        {
            // TODO unit test for the property 'Shipcomplete'
        }

        /// <summary>
        /// Test the property 'Shipdate'
        /// </summary>
        [Fact]
        public void ShipdateTest()
        {
            // TODO unit test for the property 'Shipdate'
        }

        /// <summary>
        /// Test the property 'Companycurrency'
        /// </summary>
        [Fact]
        public void CompanycurrencyTest()
        {
            // TODO unit test for the property 'Companycurrency'
        }

        /// <summary>
        /// Test the property 'Currencycode'
        /// </summary>
        [Fact]
        public void CurrencycodeTest()
        {
            // TODO unit test for the property 'Currencycode'
        }

        /// <summary>
        /// Test the property 'Currencyrate'
        /// </summary>
        [Fact]
        public void CurrencyrateTest()
        {
            // TODO unit test for the property 'Currencyrate'
        }

        /// <summary>
        /// Test the property 'Globalorderid'
        /// </summary>
        [Fact]
        public void GlobalorderidTest()
        {
            // TODO unit test for the property 'Globalorderid'
        }

        /// <summary>
        /// Test the property 'Originalshipcode'
        /// </summary>
        [Fact]
        public void OriginalshipcodeTest()
        {
            // TODO unit test for the property 'Originalshipcode'
        }

        /// <summary>
        /// Test the property 'Ordertype'
        /// </summary>
        [Fact]
        public void OrdertypeTest()
        {
            // TODO unit test for the property 'Ordertype'
        }

        /// <summary>
        /// Test the property 'Orderstatus'
        /// </summary>
        [Fact]
        public void OrderstatusTest()
        {
            // TODO unit test for the property 'Orderstatus'
        }

        /// <summary>
        /// Test the property 'Totalotherfees'
        /// </summary>
        [Fact]
        public void TotalotherfeesTest()
        {
            // TODO unit test for the property 'Totalotherfees'
        }

        /// <summary>
        /// Test the property 'Totalsales'
        /// </summary>
        [Fact]
        public void TotalsalesTest()
        {
            // TODO unit test for the property 'Totalsales'
        }

        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Fact]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }

        /// <summary>
        /// Test the property 'Shippableswitch'
        /// </summary>
        [Fact]
        public void ShippableswitchTest()
        {
            // TODO unit test for the property 'Shippableswitch'
        }

        /// <summary>
        /// Test the property 'Soldto'
        /// </summary>
        [Fact]
        public void SoldtoTest()
        {
            // TODO unit test for the property 'Soldto'
        }

        /// <summary>
        /// Test the property 'Billto'
        /// </summary>
        [Fact]
        public void BilltoTest()
        {
            // TODO unit test for the property 'Billto'
        }

        /// <summary>
        /// Test the property 'Shoptoaddress'
        /// </summary>
        [Fact]
        public void ShoptoaddressTest()
        {
            // TODO unit test for the property 'Shoptoaddress'
        }

        /// <summary>
        /// Test the property 'Lines'
        /// </summary>
        [Fact]
        public void LinesTest()
        {
            // TODO unit test for the property 'Lines'
        }

        /// <summary>
        /// Test the property 'Extendedspecs'
        /// </summary>
        [Fact]
        public void ExtendedspecsTest()
        {
            // TODO unit test for the property 'Extendedspecs'
        }

        /// <summary>
        /// Test the property 'Miscfeeline'
        /// </summary>
        [Fact]
        public void MiscfeelineTest()
        {
            // TODO unit test for the property 'Miscfeeline'
        }
    }
}
