/*
 * XI SDK Resellers
 *
 * For Resellers. Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing InvoiceDetailRequestServicerequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InvoiceDetailRequestServicerequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InvoiceDetailRequestServicerequest
        //private InvoiceDetailRequestServicerequest instance;

        public InvoiceDetailRequestServicerequestTests()
        {
            // TODO uncomment below to create an instance of InvoiceDetailRequestServicerequest
            //instance = new InvoiceDetailRequestServicerequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InvoiceDetailRequestServicerequest
        /// </summary>
        [Fact]
        public void InvoiceDetailRequestServicerequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" InvoiceDetailRequestServicerequest
            //Assert.IsType<InvoiceDetailRequestServicerequest>(instance);
        }

        /// <summary>
        /// Test the property 'Requestpreamble'
        /// </summary>
        [Fact]
        public void RequestpreambleTest()
        {
            // TODO unit test for the property 'Requestpreamble'
        }

        /// <summary>
        /// Test the property 'Invoicedetailrequest'
        /// </summary>
        [Fact]
        public void InvoicedetailrequestTest()
        {
            // TODO unit test for the property 'Invoicedetailrequest'
        }
    }
}
