/*
 * Reseller API
 *
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing MultiSKUPriceAndStockRequestServicerequestRequestpreamble
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MultiSKUPriceAndStockRequestServicerequestRequestpreambleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MultiSKUPriceAndStockRequestServicerequestRequestpreamble
        //private MultiSKUPriceAndStockRequestServicerequestRequestpreamble instance;

        public MultiSKUPriceAndStockRequestServicerequestRequestpreambleTests()
        {
            // TODO uncomment below to create an instance of MultiSKUPriceAndStockRequestServicerequestRequestpreamble
            //instance = new MultiSKUPriceAndStockRequestServicerequestRequestpreamble();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MultiSKUPriceAndStockRequestServicerequestRequestpreamble
        /// </summary>
        [Fact]
        public void MultiSKUPriceAndStockRequestServicerequestRequestpreambleInstanceTest()
        {
            // TODO uncomment below to test "IsType" MultiSKUPriceAndStockRequestServicerequestRequestpreamble
            //Assert.IsType<MultiSKUPriceAndStockRequestServicerequestRequestpreamble>(instance);
        }

        /// <summary>
        /// Test the property 'Isocountrycode'
        /// </summary>
        [Fact]
        public void IsocountrycodeTest()
        {
            // TODO unit test for the property 'Isocountrycode'
        }

        /// <summary>
        /// Test the property 'Customernumber'
        /// </summary>
        [Fact]
        public void CustomernumberTest()
        {
            // TODO unit test for the property 'Customernumber'
        }
    }
}
