/*
 * XI SDK Resellers
 *
 * For Resellers. Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing MultiSKUPriceAndStockRequestServicerequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MultiSKUPriceAndStockRequestServicerequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MultiSKUPriceAndStockRequestServicerequest
        //private MultiSKUPriceAndStockRequestServicerequest instance;

        public MultiSKUPriceAndStockRequestServicerequestTests()
        {
            // TODO uncomment below to create an instance of MultiSKUPriceAndStockRequestServicerequest
            //instance = new MultiSKUPriceAndStockRequestServicerequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MultiSKUPriceAndStockRequestServicerequest
        /// </summary>
        [Fact]
        public void MultiSKUPriceAndStockRequestServicerequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" MultiSKUPriceAndStockRequestServicerequest
            //Assert.IsType<MultiSKUPriceAndStockRequestServicerequest>(instance);
        }

        /// <summary>
        /// Test the property 'Requestpreamble'
        /// </summary>
        [Fact]
        public void RequestpreambleTest()
        {
            // TODO unit test for the property 'Requestpreamble'
        }

        /// <summary>
        /// Test the property 'Priceandstockrequest'
        /// </summary>
        [Fact]
        public void PriceandstockrequestTest()
        {
            // TODO unit test for the property 'Priceandstockrequest'
        }
    }
}
