/*
 * Reseller API
 *
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing OrderDetailResponseServiceresponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderDetailResponseServiceresponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderDetailResponseServiceresponse
        //private OrderDetailResponseServiceresponse instance;

        public OrderDetailResponseServiceresponseTests()
        {
            // TODO uncomment below to create an instance of OrderDetailResponseServiceresponse
            //instance = new OrderDetailResponseServiceresponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderDetailResponseServiceresponse
        /// </summary>
        [Fact]
        public void OrderDetailResponseServiceresponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderDetailResponseServiceresponse
            //Assert.IsType<OrderDetailResponseServiceresponse>(instance);
        }

        /// <summary>
        /// Test the property 'Responsepreamble'
        /// </summary>
        [Fact]
        public void ResponsepreambleTest()
        {
            // TODO unit test for the property 'Responsepreamble'
        }

        /// <summary>
        /// Test the property 'Orderdetailresponse'
        /// </summary>
        [Fact]
        public void OrderdetailresponseTest()
        {
            // TODO unit test for the property 'Orderdetailresponse'
        }
    }
}
