/*
 * XI Sdk Resellers
 *
 * For Resellers. Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing OrderSearchRequestServicerequestRequestpreamble
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderSearchRequestServicerequestRequestpreambleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderSearchRequestServicerequestRequestpreamble
        //private OrderSearchRequestServicerequestRequestpreamble instance;

        public OrderSearchRequestServicerequestRequestpreambleTests()
        {
            // TODO uncomment below to create an instance of OrderSearchRequestServicerequestRequestpreamble
            //instance = new OrderSearchRequestServicerequestRequestpreamble();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderSearchRequestServicerequestRequestpreamble
        /// </summary>
        [Fact]
        public void OrderSearchRequestServicerequestRequestpreambleInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderSearchRequestServicerequestRequestpreamble
            //Assert.IsType<OrderSearchRequestServicerequestRequestpreamble>(instance);
        }

        /// <summary>
        /// Test the property 'IsoCountryCode'
        /// </summary>
        [Fact]
        public void IsoCountryCodeTest()
        {
            // TODO unit test for the property 'IsoCountryCode'
        }

        /// <summary>
        /// Test the property 'CustomerNumber'
        /// </summary>
        [Fact]
        public void CustomerNumberTest()
        {
            // TODO unit test for the property 'CustomerNumber'
        }
    }
}
