/*
 * Reseller API
 *
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing OrderCreateResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderCreateResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderCreateResponse
        //private OrderCreateResponse instance;

        public OrderCreateResponseTests()
        {
            // TODO uncomment below to create an instance of OrderCreateResponse
            //instance = new OrderCreateResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderCreateResponse
        /// </summary>
        [Fact]
        public void OrderCreateResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderCreateResponse
            //Assert.IsType<OrderCreateResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Serviceresponse'
        /// </summary>
        [Fact]
        public void ServiceresponseTest()
        {
            // TODO unit test for the property 'Serviceresponse'
        }
    }
}
