/*
 * Reseller API
 *
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing OrderCancelResponseServiceresponseResponsepreamble
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderCancelResponseServiceresponseResponsepreambleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderCancelResponseServiceresponseResponsepreamble
        //private OrderCancelResponseServiceresponseResponsepreamble instance;

        public OrderCancelResponseServiceresponseResponsepreambleTests()
        {
            // TODO uncomment below to create an instance of OrderCancelResponseServiceresponseResponsepreamble
            //instance = new OrderCancelResponseServiceresponseResponsepreamble();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderCancelResponseServiceresponseResponsepreamble
        /// </summary>
        [Fact]
        public void OrderCancelResponseServiceresponseResponsepreambleInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderCancelResponseServiceresponseResponsepreamble
            //Assert.IsType<OrderCancelResponseServiceresponseResponsepreamble>(instance);
        }

        /// <summary>
        /// Test the property 'RequestStatus'
        /// </summary>
        [Fact]
        public void RequestStatusTest()
        {
            // TODO unit test for the property 'RequestStatus'
        }

        /// <summary>
        /// Test the property 'ReturnCode'
        /// </summary>
        [Fact]
        public void ReturnCodeTest()
        {
            // TODO unit test for the property 'ReturnCode'
        }

        /// <summary>
        /// Test the property 'ReturnMessage'
        /// </summary>
        [Fact]
        public void ReturnMessageTest()
        {
            // TODO unit test for the property 'ReturnMessage'
        }
    }
}
