/*
 * Reseller API
 *
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInnerPackagedetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInnerPackagedetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInnerPackagedetails
        //private OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInnerPackagedetails instance;

        public OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInnerPackagedetailsTests()
        {
            // TODO uncomment below to create an instance of OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInnerPackagedetails
            //instance = new OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInnerPackagedetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInnerPackagedetails
        /// </summary>
        [Fact]
        public void OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInnerPackagedetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInnerPackagedetails
            //Assert.IsType<OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerShipmentdetailsInnerPackagedetails>(instance);
        }

        /// <summary>
        /// Test the property 'Trackingnumber'
        /// </summary>
        [Fact]
        public void TrackingnumberTest()
        {
            // TODO unit test for the property 'Trackingnumber'
        }

        /// <summary>
        /// Test the property 'Packageweight'
        /// </summary>
        [Fact]
        public void PackageweightTest()
        {
            // TODO unit test for the property 'Packageweight'
        }

        /// <summary>
        /// Test the property 'Cartonnumber'
        /// </summary>
        [Fact]
        public void CartonnumberTest()
        {
            // TODO unit test for the property 'Cartonnumber'
        }

        /// <summary>
        /// Test the property 'Quantityinbox'
        /// </summary>
        [Fact]
        public void QuantityinboxTest()
        {
            // TODO unit test for the property 'Quantityinbox'
        }
    }
}
