/*
 * XI Sdk Resellers
 *
 * For Resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing OrderCreateV7RequestLinesInnerWarrantyInfoInnerSerialInfoInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderCreateV7RequestLinesInnerWarrantyInfoInnerSerialInfoInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderCreateV7RequestLinesInnerWarrantyInfoInnerSerialInfoInner
        //private OrderCreateV7RequestLinesInnerWarrantyInfoInnerSerialInfoInner instance;

        public OrderCreateV7RequestLinesInnerWarrantyInfoInnerSerialInfoInnerTests()
        {
            // TODO uncomment below to create an instance of OrderCreateV7RequestLinesInnerWarrantyInfoInnerSerialInfoInner
            //instance = new OrderCreateV7RequestLinesInnerWarrantyInfoInnerSerialInfoInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderCreateV7RequestLinesInnerWarrantyInfoInnerSerialInfoInner
        /// </summary>
        [Fact]
        public void OrderCreateV7RequestLinesInnerWarrantyInfoInnerSerialInfoInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderCreateV7RequestLinesInnerWarrantyInfoInnerSerialInfoInner
            //Assert.IsType<OrderCreateV7RequestLinesInnerWarrantyInfoInnerSerialInfoInner>(instance);
        }

        /// <summary>
        /// Test the property 'DateOfPurchase'
        /// </summary>
        [Fact]
        public void DateOfPurchaseTest()
        {
            // TODO unit test for the property 'DateOfPurchase'
        }

        /// <summary>
        /// Test the property 'ShipDate'
        /// </summary>
        [Fact]
        public void ShipDateTest()
        {
            // TODO unit test for the property 'ShipDate'
        }

        /// <summary>
        /// Test the property 'PrimarySerialNumber'
        /// </summary>
        [Fact]
        public void PrimarySerialNumberTest()
        {
            // TODO unit test for the property 'PrimarySerialNumber'
        }

        /// <summary>
        /// Test the property 'SecondarySerialNumber'
        /// </summary>
        [Fact]
        public void SecondarySerialNumberTest()
        {
            // TODO unit test for the property 'SecondarySerialNumber'
        }
    }
}
