/*
 * Reseller API
 *
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing OrderCreateResponseServiceresponseOrdercreateresponseInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderCreateResponseServiceresponseOrdercreateresponseInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderCreateResponseServiceresponseOrdercreateresponseInner
        //private OrderCreateResponseServiceresponseOrdercreateresponseInner instance;

        public OrderCreateResponseServiceresponseOrdercreateresponseInnerTests()
        {
            // TODO uncomment below to create an instance of OrderCreateResponseServiceresponseOrdercreateresponseInner
            //instance = new OrderCreateResponseServiceresponseOrdercreateresponseInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderCreateResponseServiceresponseOrdercreateresponseInner
        /// </summary>
        [Fact]
        public void OrderCreateResponseServiceresponseOrdercreateresponseInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderCreateResponseServiceresponseOrdercreateresponseInner
            //Assert.IsType<OrderCreateResponseServiceresponseOrdercreateresponseInner>(instance);
        }

        /// <summary>
        /// Test the property 'Numberoflineswithsuccess'
        /// </summary>
        [Fact]
        public void NumberoflineswithsuccessTest()
        {
            // TODO unit test for the property 'Numberoflineswithsuccess'
        }

        /// <summary>
        /// Test the property 'Numberoflineswitherror'
        /// </summary>
        [Fact]
        public void NumberoflineswitherrorTest()
        {
            // TODO unit test for the property 'Numberoflineswitherror'
        }

        /// <summary>
        /// Test the property 'Numberoflineswithwarning'
        /// </summary>
        [Fact]
        public void NumberoflineswithwarningTest()
        {
            // TODO unit test for the property 'Numberoflineswithwarning'
        }

        /// <summary>
        /// Test the property 'Globalorderid'
        /// </summary>
        [Fact]
        public void GlobalorderidTest()
        {
            // TODO unit test for the property 'Globalorderid'
        }

        /// <summary>
        /// Test the property 'Ordertype'
        /// </summary>
        [Fact]
        public void OrdertypeTest()
        {
            // TODO unit test for the property 'Ordertype'
        }

        /// <summary>
        /// Test the property 'Ordertimestamp'
        /// </summary>
        [Fact]
        public void OrdertimestampTest()
        {
            // TODO unit test for the property 'Ordertimestamp'
        }

        /// <summary>
        /// Test the property 'Invoicingsystemorderid'
        /// </summary>
        [Fact]
        public void InvoicingsystemorderidTest()
        {
            // TODO unit test for the property 'Invoicingsystemorderid'
        }

        /// <summary>
        /// Test the property 'Taxamount'
        /// </summary>
        [Fact]
        public void TaxamountTest()
        {
            // TODO unit test for the property 'Taxamount'
        }

        /// <summary>
        /// Test the property 'Freightamount'
        /// </summary>
        [Fact]
        public void FreightamountTest()
        {
            // TODO unit test for the property 'Freightamount'
        }

        /// <summary>
        /// Test the property 'Orderamount'
        /// </summary>
        [Fact]
        public void OrderamountTest()
        {
            // TODO unit test for the property 'Orderamount'
        }

        /// <summary>
        /// Test the property 'Lines'
        /// </summary>
        [Fact]
        public void LinesTest()
        {
            // TODO unit test for the property 'Lines'
        }
    }
}
