/*
 * Reseller API
 *
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing PostQuoteToOrderV6400Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostQuoteToOrderV6400ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostQuoteToOrderV6400Response
        //private PostQuoteToOrderV6400Response instance;

        public PostQuoteToOrderV6400ResponseTests()
        {
            // TODO uncomment below to create an instance of PostQuoteToOrderV6400Response
            //instance = new PostQuoteToOrderV6400Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostQuoteToOrderV6400Response
        /// </summary>
        [Fact]
        public void PostQuoteToOrderV6400ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PostQuoteToOrderV6400Response
            //Assert.IsType<PostQuoteToOrderV6400Response>(instance);
        }

        /// <summary>
        /// Test the property 'Traceid'
        /// </summary>
        [Fact]
        public void TraceidTest()
        {
            // TODO unit test for the property 'Traceid'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Fields'
        /// </summary>
        [Fact]
        public void FieldsTest()
        {
            // TODO unit test for the property 'Fields'
        }
    }
}
