/*
 * XI Sdk Resellers
 *
 * For resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing PostAsyncOrderCreateV7400Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostAsyncOrderCreateV7400ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostAsyncOrderCreateV7400Response
        //private PostAsyncOrderCreateV7400Response instance;

        public PostAsyncOrderCreateV7400ResponseTests()
        {
            // TODO uncomment below to create an instance of PostAsyncOrderCreateV7400Response
            //instance = new PostAsyncOrderCreateV7400Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostAsyncOrderCreateV7400Response
        /// </summary>
        [Fact]
        public void PostAsyncOrderCreateV7400ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PostAsyncOrderCreateV7400Response
            //Assert.IsType<PostAsyncOrderCreateV7400Response>(instance);
        }

        /// <summary>
        /// Test the property 'Traceid'
        /// </summary>
        [Fact]
        public void TraceidTest()
        {
            // TODO unit test for the property 'Traceid'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Fields'
        /// </summary>
        [Fact]
        public void FieldsTest()
        {
            // TODO unit test for the property 'Fields'
        }
    }
}
