/*
 * XI SDK Resellers
 *
 * For Resellers. Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing ProductSearchRequestServicerequestProductsearchrequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductSearchRequestServicerequestProductsearchrequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductSearchRequestServicerequestProductsearchrequest
        //private ProductSearchRequestServicerequestProductsearchrequest instance;

        public ProductSearchRequestServicerequestProductsearchrequestTests()
        {
            // TODO uncomment below to create an instance of ProductSearchRequestServicerequestProductsearchrequest
            //instance = new ProductSearchRequestServicerequestProductsearchrequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductSearchRequestServicerequestProductsearchrequest
        /// </summary>
        [Fact]
        public void ProductSearchRequestServicerequestProductsearchrequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductSearchRequestServicerequestProductsearchrequest
            //Assert.IsType<ProductSearchRequestServicerequestProductsearchrequest>(instance);
        }

        /// <summary>
        /// Test the property 'Searchcriteria'
        /// </summary>
        [Fact]
        public void SearchcriteriaTest()
        {
            // TODO unit test for the property 'Searchcriteria'
        }
    }
}
