/*
 * XI Sdk Resellers
 *
 * For resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing ProductDetailResponseTechnicalSpecificationsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductDetailResponseTechnicalSpecificationsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductDetailResponseTechnicalSpecificationsInner
        //private ProductDetailResponseTechnicalSpecificationsInner instance;

        public ProductDetailResponseTechnicalSpecificationsInnerTests()
        {
            // TODO uncomment below to create an instance of ProductDetailResponseTechnicalSpecificationsInner
            //instance = new ProductDetailResponseTechnicalSpecificationsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductDetailResponseTechnicalSpecificationsInner
        /// </summary>
        [Fact]
        public void ProductDetailResponseTechnicalSpecificationsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductDetailResponseTechnicalSpecificationsInner
            //Assert.IsType<ProductDetailResponseTechnicalSpecificationsInner>(instance);
        }

        /// <summary>
        /// Test the property 'HeaderName'
        /// </summary>
        [Fact]
        public void HeaderNameTest()
        {
            // TODO unit test for the property 'HeaderName'
        }

        /// <summary>
        /// Test the property 'AttributeName'
        /// </summary>
        [Fact]
        public void AttributeNameTest()
        {
            // TODO unit test for the property 'AttributeName'
        }

        /// <summary>
        /// Test the property 'AttributeDisplay'
        /// </summary>
        [Fact]
        public void AttributeDisplayTest()
        {
            // TODO unit test for the property 'AttributeDisplay'
        }

        /// <summary>
        /// Test the property 'AttributeValue'
        /// </summary>
        [Fact]
        public void AttributeValueTest()
        {
            // TODO unit test for the property 'AttributeValue'
        }
    }
}
