/*
 * XI SDK Resellers
 *
 * For Resellers. Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing QuoteDetailsResponseQuoteDetailResponseRetrieveQuoteResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class QuoteDetailsResponseQuoteDetailResponseRetrieveQuoteResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for QuoteDetailsResponseQuoteDetailResponseRetrieveQuoteResponse
        //private QuoteDetailsResponseQuoteDetailResponseRetrieveQuoteResponse instance;

        public QuoteDetailsResponseQuoteDetailResponseRetrieveQuoteResponseTests()
        {
            // TODO uncomment below to create an instance of QuoteDetailsResponseQuoteDetailResponseRetrieveQuoteResponse
            //instance = new QuoteDetailsResponseQuoteDetailResponseRetrieveQuoteResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of QuoteDetailsResponseQuoteDetailResponseRetrieveQuoteResponse
        /// </summary>
        [Fact]
        public void QuoteDetailsResponseQuoteDetailResponseRetrieveQuoteResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" QuoteDetailsResponseQuoteDetailResponseRetrieveQuoteResponse
            //Assert.IsType<QuoteDetailsResponseQuoteDetailResponseRetrieveQuoteResponse>(instance);
        }

        /// <summary>
        /// Test the property 'QuoteGuid'
        /// </summary>
        [Fact]
        public void QuoteGuidTest()
        {
            // TODO unit test for the property 'QuoteGuid'
        }

        /// <summary>
        /// Test the property 'QuoteName'
        /// </summary>
        [Fact]
        public void QuoteNameTest()
        {
            // TODO unit test for the property 'QuoteName'
        }

        /// <summary>
        /// Test the property 'QuoteNumber'
        /// </summary>
        [Fact]
        public void QuoteNumberTest()
        {
            // TODO unit test for the property 'QuoteNumber'
        }

        /// <summary>
        /// Test the property 'QuoteExpiryDate'
        /// </summary>
        [Fact]
        public void QuoteExpiryDateTest()
        {
            // TODO unit test for the property 'QuoteExpiryDate'
        }

        /// <summary>
        /// Test the property 'RevisionNumber'
        /// </summary>
        [Fact]
        public void RevisionNumberTest()
        {
            // TODO unit test for the property 'RevisionNumber'
        }

        /// <summary>
        /// Test the property 'IntroPreamble'
        /// </summary>
        [Fact]
        public void IntroPreambleTest()
        {
            // TODO unit test for the property 'IntroPreamble'
        }

        /// <summary>
        /// Test the property 'PurchaseInstructions'
        /// </summary>
        [Fact]
        public void PurchaseInstructionsTest()
        {
            // TODO unit test for the property 'PurchaseInstructions'
        }

        /// <summary>
        /// Test the property 'LegalTerms'
        /// </summary>
        [Fact]
        public void LegalTermsTest()
        {
            // TODO unit test for the property 'LegalTerms'
        }

        /// <summary>
        /// Test the property 'CurrencyCode'
        /// </summary>
        [Fact]
        public void CurrencyCodeTest()
        {
            // TODO unit test for the property 'CurrencyCode'
        }

        /// <summary>
        /// Test the property 'PriceDeviationId'
        /// </summary>
        [Fact]
        public void PriceDeviationIdTest()
        {
            // TODO unit test for the property 'PriceDeviationId'
        }

        /// <summary>
        /// Test the property 'PriceDeviationStartDate'
        /// </summary>
        [Fact]
        public void PriceDeviationStartDateTest()
        {
            // TODO unit test for the property 'PriceDeviationStartDate'
        }

        /// <summary>
        /// Test the property 'PriceDeviationExpiryDate'
        /// </summary>
        [Fact]
        public void PriceDeviationExpiryDateTest()
        {
            // TODO unit test for the property 'PriceDeviationExpiryDate'
        }

        /// <summary>
        /// Test the property 'CustomerNeed'
        /// </summary>
        [Fact]
        public void CustomerNeedTest()
        {
            // TODO unit test for the property 'CustomerNeed'
        }

        /// <summary>
        /// Test the property 'SolutionProposed'
        /// </summary>
        [Fact]
        public void SolutionProposedTest()
        {
            // TODO unit test for the property 'SolutionProposed'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }

        /// <summary>
        /// Test the property 'Modified'
        /// </summary>
        [Fact]
        public void ModifiedTest()
        {
            // TODO unit test for the property 'Modified'
        }

        /// <summary>
        /// Test the property 'LeasingCalculations'
        /// </summary>
        [Fact]
        public void LeasingCalculationsTest()
        {
            // TODO unit test for the property 'LeasingCalculations'
        }

        /// <summary>
        /// Test the property 'LeasingInstructions'
        /// </summary>
        [Fact]
        public void LeasingInstructionsTest()
        {
            // TODO unit test for the property 'LeasingInstructions'
        }

        /// <summary>
        /// Test the property 'AccountInfo'
        /// </summary>
        [Fact]
        public void AccountInfoTest()
        {
            // TODO unit test for the property 'AccountInfo'
        }

        /// <summary>
        /// Test the property 'ContactInfo'
        /// </summary>
        [Fact]
        public void ContactInfoTest()
        {
            // TODO unit test for the property 'ContactInfo'
        }

        /// <summary>
        /// Test the property 'VendorAttributes'
        /// </summary>
        [Fact]
        public void VendorAttributesTest()
        {
            // TODO unit test for the property 'VendorAttributes'
        }

        /// <summary>
        /// Test the property 'EndUser'
        /// </summary>
        [Fact]
        public void EndUserTest()
        {
            // TODO unit test for the property 'EndUser'
        }

        /// <summary>
        /// Test the property 'QuoteProductList'
        /// </summary>
        [Fact]
        public void QuoteProductListTest()
        {
            // TODO unit test for the property 'QuoteProductList'
        }

        /// <summary>
        /// Test the property 'TotalQuoteProductCount'
        /// </summary>
        [Fact]
        public void TotalQuoteProductCountTest()
        {
            // TODO unit test for the property 'TotalQuoteProductCount'
        }

        /// <summary>
        /// Test the property 'TotalExtendedMsrp'
        /// </summary>
        [Fact]
        public void TotalExtendedMsrpTest()
        {
            // TODO unit test for the property 'TotalExtendedMsrp'
        }

        /// <summary>
        /// Test the property 'TotalQuantity'
        /// </summary>
        [Fact]
        public void TotalQuantityTest()
        {
            // TODO unit test for the property 'TotalQuantity'
        }

        /// <summary>
        /// Test the property 'TotalExtendedQuotePrice'
        /// </summary>
        [Fact]
        public void TotalExtendedQuotePriceTest()
        {
            // TODO unit test for the property 'TotalExtendedQuotePrice'
        }
    }
}
