/*
 * Reseller API
 *
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseEndUser
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseEndUserTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseEndUser
        //private QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseEndUser instance;

        public QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseEndUserTests()
        {
            // TODO uncomment below to create an instance of QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseEndUser
            //instance = new QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseEndUser();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseEndUser
        /// </summary>
        [Fact]
        public void QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseEndUserInstanceTest()
        {
            // TODO uncomment below to test "IsType" QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseEndUser
            //Assert.IsType<QuoteDetailsQuoteDetailResponseRetrieveQuoteResponseEndUser>(instance);
        }

        /// <summary>
        /// Test the property 'EndUserName'
        /// </summary>
        [Fact]
        public void EndUserNameTest()
        {
            // TODO unit test for the property 'EndUserName'
        }

        /// <summary>
        /// Test the property 'EndUserAddress'
        /// </summary>
        [Fact]
        public void EndUserAddressTest()
        {
            // TODO unit test for the property 'EndUserAddress'
        }

        /// <summary>
        /// Test the property 'EndUserAddress2'
        /// </summary>
        [Fact]
        public void EndUserAddress2Test()
        {
            // TODO unit test for the property 'EndUserAddress2'
        }

        /// <summary>
        /// Test the property 'EndUserAddress3'
        /// </summary>
        [Fact]
        public void EndUserAddress3Test()
        {
            // TODO unit test for the property 'EndUserAddress3'
        }

        /// <summary>
        /// Test the property 'EndUserCity'
        /// </summary>
        [Fact]
        public void EndUserCityTest()
        {
            // TODO unit test for the property 'EndUserCity'
        }

        /// <summary>
        /// Test the property 'EndUserState'
        /// </summary>
        [Fact]
        public void EndUserStateTest()
        {
            // TODO unit test for the property 'EndUserState'
        }

        /// <summary>
        /// Test the property 'EndUserEmail'
        /// </summary>
        [Fact]
        public void EndUserEmailTest()
        {
            // TODO unit test for the property 'EndUserEmail'
        }

        /// <summary>
        /// Test the property 'EndUserPhone'
        /// </summary>
        [Fact]
        public void EndUserPhoneTest()
        {
            // TODO unit test for the property 'EndUserPhone'
        }

        /// <summary>
        /// Test the property 'EndUserZipCode'
        /// </summary>
        [Fact]
        public void EndUserZipCodeTest()
        {
            // TODO unit test for the property 'EndUserZipCode'
        }

        /// <summary>
        /// Test the property 'EndUserContactName'
        /// </summary>
        [Fact]
        public void EndUserContactNameTest()
        {
            // TODO unit test for the property 'EndUserContactName'
        }

        /// <summary>
        /// Test the property 'EndUserMarketSegment'
        /// </summary>
        [Fact]
        public void EndUserMarketSegmentTest()
        {
            // TODO unit test for the property 'EndUserMarketSegment'
        }
    }
}
