/*
 * XI Sdk Resellers
 *
 * For Ingram Micro Resellers. Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing QuoteToOrderDetailsDTOLinesInnerVmfAdditionalAttributesLinesInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class QuoteToOrderDetailsDTOLinesInnerVmfAdditionalAttributesLinesInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for QuoteToOrderDetailsDTOLinesInnerVmfAdditionalAttributesLinesInner
        //private QuoteToOrderDetailsDTOLinesInnerVmfAdditionalAttributesLinesInner instance;

        public QuoteToOrderDetailsDTOLinesInnerVmfAdditionalAttributesLinesInnerTests()
        {
            // TODO uncomment below to create an instance of QuoteToOrderDetailsDTOLinesInnerVmfAdditionalAttributesLinesInner
            //instance = new QuoteToOrderDetailsDTOLinesInnerVmfAdditionalAttributesLinesInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of QuoteToOrderDetailsDTOLinesInnerVmfAdditionalAttributesLinesInner
        /// </summary>
        [Fact]
        public void QuoteToOrderDetailsDTOLinesInnerVmfAdditionalAttributesLinesInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" QuoteToOrderDetailsDTOLinesInnerVmfAdditionalAttributesLinesInner
            //Assert.IsType<QuoteToOrderDetailsDTOLinesInnerVmfAdditionalAttributesLinesInner>(instance);
        }

        /// <summary>
        /// Test the property 'AttributeName'
        /// </summary>
        [Fact]
        public void AttributeNameTest()
        {
            // TODO unit test for the property 'AttributeName'
        }

        /// <summary>
        /// Test the property 'AttributeValue'
        /// </summary>
        [Fact]
        public void AttributeValueTest()
        {
            // TODO unit test for the property 'AttributeValue'
        }

        /// <summary>
        /// Test the property 'AttributeDescription'
        /// </summary>
        [Fact]
        public void AttributeDescriptionTest()
        {
            // TODO unit test for the property 'AttributeDescription'
        }
    }
}
