/*
 * XI Sdk Resellers
 *
 * For Resellers. Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing QuoteListResponseQuoteSearchResponseResponsePreamble
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class QuoteListResponseQuoteSearchResponseResponsePreambleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for QuoteListResponseQuoteSearchResponseResponsePreamble
        //private QuoteListResponseQuoteSearchResponseResponsePreamble instance;

        public QuoteListResponseQuoteSearchResponseResponsePreambleTests()
        {
            // TODO uncomment below to create an instance of QuoteListResponseQuoteSearchResponseResponsePreamble
            //instance = new QuoteListResponseQuoteSearchResponseResponsePreamble();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of QuoteListResponseQuoteSearchResponseResponsePreamble
        /// </summary>
        [Fact]
        public void QuoteListResponseQuoteSearchResponseResponsePreambleInstanceTest()
        {
            // TODO uncomment below to test "IsType" QuoteListResponseQuoteSearchResponseResponsePreamble
            //Assert.IsType<QuoteListResponseQuoteSearchResponseResponsePreamble>(instance);
        }

        /// <summary>
        /// Test the property 'ResponseStatus'
        /// </summary>
        [Fact]
        public void ResponseStatusTest()
        {
            // TODO unit test for the property 'ResponseStatus'
        }

        /// <summary>
        /// Test the property 'ResponseStatusCode'
        /// </summary>
        [Fact]
        public void ResponseStatusCodeTest()
        {
            // TODO unit test for the property 'ResponseStatusCode'
        }

        /// <summary>
        /// Test the property 'ResponseMessage'
        /// </summary>
        [Fact]
        public void ResponseMessageTest()
        {
            // TODO unit test for the property 'ResponseMessage'
        }
    }
}
