/*
 * Reseller API
 *
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing QuoteDetailsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class QuoteDetailsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for QuoteDetailsRequest
        //private QuoteDetailsRequest instance;

        public QuoteDetailsRequestTests()
        {
            // TODO uncomment below to create an instance of QuoteDetailsRequest
            //instance = new QuoteDetailsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of QuoteDetailsRequest
        /// </summary>
        [Fact]
        public void QuoteDetailsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" QuoteDetailsRequest
            //Assert.IsType<QuoteDetailsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'QuoteProductsRequest'
        /// </summary>
        [Fact]
        public void QuoteProductsRequestTest()
        {
            // TODO unit test for the property 'QuoteProductsRequest'
        }
    }
}
