/*
 * XI Sdk Resellers
 *
 * For Ingram Micro Resellers. Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing QuoteToOrderDetailsDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class QuoteToOrderDetailsDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for QuoteToOrderDetailsDTO
        //private QuoteToOrderDetailsDTO instance;

        public QuoteToOrderDetailsDTOTests()
        {
            // TODO uncomment below to create an instance of QuoteToOrderDetailsDTO
            //instance = new QuoteToOrderDetailsDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of QuoteToOrderDetailsDTO
        /// </summary>
        [Fact]
        public void QuoteToOrderDetailsDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" QuoteToOrderDetailsDTO
            //Assert.IsType<QuoteToOrderDetailsDTO>(instance);
        }

        /// <summary>
        /// Test the property 'QuoteNumber'
        /// </summary>
        [Fact]
        public void QuoteNumberTest()
        {
            // TODO unit test for the property 'QuoteNumber'
        }

        /// <summary>
        /// Test the property 'CustomerOrderNumber'
        /// </summary>
        [Fact]
        public void CustomerOrderNumberTest()
        {
            // TODO unit test for the property 'CustomerOrderNumber'
        }

        /// <summary>
        /// Test the property 'EnduserOrderNumber'
        /// </summary>
        [Fact]
        public void EnduserOrderNumberTest()
        {
            // TODO unit test for the property 'EnduserOrderNumber'
        }

        /// <summary>
        /// Test the property 'BillToAddressId'
        /// </summary>
        [Fact]
        public void BillToAddressIdTest()
        {
            // TODO unit test for the property 'BillToAddressId'
        }

        /// <summary>
        /// Test the property 'EndUserInfo'
        /// </summary>
        [Fact]
        public void EndUserInfoTest()
        {
            // TODO unit test for the property 'EndUserInfo'
        }

        /// <summary>
        /// Test the property 'ShipToInfo'
        /// </summary>
        [Fact]
        public void ShipToInfoTest()
        {
            // TODO unit test for the property 'ShipToInfo'
        }

        /// <summary>
        /// Test the property 'AdditionalAttributes'
        /// </summary>
        [Fact]
        public void AdditionalAttributesTest()
        {
            // TODO unit test for the property 'AdditionalAttributes'
        }

        /// <summary>
        /// Test the property 'VmfadditionalAttributes'
        /// </summary>
        [Fact]
        public void VmfadditionalAttributesTest()
        {
            // TODO unit test for the property 'VmfadditionalAttributes'
        }

        /// <summary>
        /// Test the property 'Lines'
        /// </summary>
        [Fact]
        public void LinesTest()
        {
            // TODO unit test for the property 'Lines'
        }
    }
}
