/*
 * Reseller API Documentation
 *
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.csharp.Model;
using xi.sdk.resellers.csharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.csharp.Test.Model
{
    /// <summary>
    ///  Class for testing OrderModifyRequestServicerequestOrdermodifyrequestLinedataInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderModifyRequestServicerequestOrdermodifyrequestLinedataInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderModifyRequestServicerequestOrdermodifyrequestLinedataInner
        //private OrderModifyRequestServicerequestOrdermodifyrequestLinedataInner instance;

        public OrderModifyRequestServicerequestOrdermodifyrequestLinedataInnerTests()
        {
            // TODO uncomment below to create an instance of OrderModifyRequestServicerequestOrdermodifyrequestLinedataInner
            //instance = new OrderModifyRequestServicerequestOrdermodifyrequestLinedataInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderModifyRequestServicerequestOrdermodifyrequestLinedataInner
        /// </summary>
        [Fact]
        public void OrderModifyRequestServicerequestOrdermodifyrequestLinedataInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderModifyRequestServicerequestOrdermodifyrequestLinedataInner
            //Assert.IsType<OrderModifyRequestServicerequestOrdermodifyrequestLinedataInner>(instance);
        }

        /// <summary>
        /// Test the property 'Addlineorupdateline'
        /// </summary>
        [Fact]
        public void AddlineorupdatelineTest()
        {
            // TODO unit test for the property 'Addlineorupdateline'
        }

        /// <summary>
        /// Test the property 'Linenumber'
        /// </summary>
        [Fact]
        public void LinenumberTest()
        {
            // TODO unit test for the property 'Linenumber'
        }

        /// <summary>
        /// Test the property 'Customerlinenumber'
        /// </summary>
        [Fact]
        public void CustomerlinenumberTest()
        {
            // TODO unit test for the property 'Customerlinenumber'
        }

        /// <summary>
        /// Test the property 'Ingrampartnumber'
        /// </summary>
        [Fact]
        public void IngrampartnumberTest()
        {
            // TODO unit test for the property 'Ingrampartnumber'
        }

        /// <summary>
        /// Test the property 'Quantityordered'
        /// </summary>
        [Fact]
        public void QuantityorderedTest()
        {
            // TODO unit test for the property 'Quantityordered'
        }

        /// <summary>
        /// Test the property 'Customerpartnumber'
        /// </summary>
        [Fact]
        public void CustomerpartnumberTest()
        {
            // TODO unit test for the property 'Customerpartnumber'
        }

        /// <summary>
        /// Test the property 'Linetype'
        /// </summary>
        [Fact]
        public void LinetypeTest()
        {
            // TODO unit test for the property 'Linetype'
        }
    }
}
