/*
 * Reseller API Documentation
 *
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.csharp.Model;
using xi.sdk.resellers.csharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.csharp.Test.Model
{
    /// <summary>
    ///  Class for testing ProductSearchRequestServicerequestRequestpreamble
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductSearchRequestServicerequestRequestpreambleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductSearchRequestServicerequestRequestpreamble
        //private ProductSearchRequestServicerequestRequestpreamble instance;

        public ProductSearchRequestServicerequestRequestpreambleTests()
        {
            // TODO uncomment below to create an instance of ProductSearchRequestServicerequestRequestpreamble
            //instance = new ProductSearchRequestServicerequestRequestpreamble();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductSearchRequestServicerequestRequestpreamble
        /// </summary>
        [Fact]
        public void ProductSearchRequestServicerequestRequestpreambleInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductSearchRequestServicerequestRequestpreamble
            //Assert.IsType<ProductSearchRequestServicerequestRequestpreamble>(instance);
        }

        /// <summary>
        /// Test the property 'Isocountrycode'
        /// </summary>
        [Fact]
        public void IsocountrycodeTest()
        {
            // TODO unit test for the property 'Isocountrycode'
        }

        /// <summary>
        /// Test the property 'Customernumber'
        /// </summary>
        [Fact]
        public void CustomernumberTest()
        {
            // TODO unit test for the property 'Customernumber'
        }

        /// <summary>
        /// Test the property 'Vendornumber'
        /// </summary>
        [Fact]
        public void VendornumberTest()
        {
            // TODO unit test for the property 'Vendornumber'
        }
    }
}
