/*
 * Reseller API Documentation
 *
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.csharp.Model;
using xi.sdk.resellers.csharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.csharp.Test.Model
{
    /// <summary>
    ///  Class for testing QuoteListRequestQuoteSearchRequestRequestPreamble
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class QuoteListRequestQuoteSearchRequestRequestPreambleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for QuoteListRequestQuoteSearchRequestRequestPreamble
        //private QuoteListRequestQuoteSearchRequestRequestPreamble instance;

        public QuoteListRequestQuoteSearchRequestRequestPreambleTests()
        {
            // TODO uncomment below to create an instance of QuoteListRequestQuoteSearchRequestRequestPreamble
            //instance = new QuoteListRequestQuoteSearchRequestRequestPreamble();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of QuoteListRequestQuoteSearchRequestRequestPreamble
        /// </summary>
        [Fact]
        public void QuoteListRequestQuoteSearchRequestRequestPreambleInstanceTest()
        {
            // TODO uncomment below to test "IsType" QuoteListRequestQuoteSearchRequestRequestPreamble
            //Assert.IsType<QuoteListRequestQuoteSearchRequestRequestPreamble>(instance);
        }

        /// <summary>
        /// Test the property 'CustomerNumber'
        /// </summary>
        [Fact]
        public void CustomerNumberTest()
        {
            // TODO unit test for the property 'CustomerNumber'
        }

        /// <summary>
        /// Test the property 'CustomerContact'
        /// </summary>
        [Fact]
        public void CustomerContactTest()
        {
            // TODO unit test for the property 'CustomerContact'
        }

        /// <summary>
        /// Test the property 'IsoCountryCode'
        /// </summary>
        [Fact]
        public void IsoCountryCodeTest()
        {
            // TODO unit test for the property 'IsoCountryCode'
        }
    }
}
