/*
 * Reseller API Documentation
 *
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.csharp.Model;
using xi.sdk.resellers.csharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.csharp.Test.Model
{
    /// <summary>
    ///  Class for testing ReturnsCreateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReturnsCreateRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ReturnsCreateRequest
        //private ReturnsCreateRequest instance;

        public ReturnsCreateRequestTests()
        {
            // TODO uncomment below to create an instance of ReturnsCreateRequest
            //instance = new ReturnsCreateRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReturnsCreateRequest
        /// </summary>
        [Fact]
        public void ReturnsCreateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ReturnsCreateRequest
            //Assert.IsType<ReturnsCreateRequest>(instance);
        }

        /// <summary>
        /// Test the property 'List'
        /// </summary>
        [Fact]
        public void ListTest()
        {
            // TODO unit test for the property 'List'
        }
    }
}
