/*
 * Reseller API Documentation
 *
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using xi.sdk.resellers.csharp.Client;
using xi.sdk.resellers.csharp.Api;
// uncomment below to import models
//using xi.sdk.resellers.csharp.Model;

namespace xi.sdk.resellers.csharp.Test.Api
{
    /// <summary>
    ///  Class for testing OrdersV5Api
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class OrdersV5ApiTests : IDisposable
    {
        private OrdersV5Api instance;

        public OrdersV5ApiTests()
        {
            instance = new OrdersV5Api();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrdersV5Api
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' OrdersV5Api
            //Assert.IsType<OrdersV5Api>(instance);
        }

        /// <summary>
        /// Test DeleteOrdersOrderNumber
        /// </summary>
        [Fact]
        public void DeleteOrdersOrderNumberTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string ordernumber = null;
            //string customerNumber = null;
            //string isoCountryCode = null;
            //string entryDate = null;
            //var response = instance.DeleteOrdersOrderNumber(ordernumber, customerNumber, isoCountryCode, entryDate);
            //Assert.IsType<OrderCancelResponse>(response);
        }

        /// <summary>
        /// Test GetOrdersSearch
        /// </summary>
        [Fact]
        public void GetOrdersSearchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string customerNumber = null;
            //string isocountrycode = null;
            //string? ordernumber = null;
            //string? customerordernumber = null;
            //string? orderstatus = null;
            //DateTime? startcreatetimestamp = null;
            //DateTime? endcreatetimestamp = null;
            //int? pagesize = null;
            //int? pagenumber = null;
            //var response = instance.GetOrdersSearch(customerNumber, isocountrycode, ordernumber, customerordernumber, orderstatus, startcreatetimestamp, endcreatetimestamp, pagesize, pagenumber);
            //Assert.IsType<OrderSearchResponse>(response);
        }

        /// <summary>
        /// Test GetV5OrdersDetails
        /// </summary>
        [Fact]
        public void GetV5OrdersDetailsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string ordernumber = null;
            //string customernumber = null;
            //string isocountrycode = null;
            //string? customerordernumber = null;
            //DateTime? startcreatetimestamp = null;
            //string? endcreatetimestamp = null;
            //string? simulate = null;
            //var response = instance.GetV5OrdersDetails(ordernumber, customernumber, isocountrycode, customerordernumber, startcreatetimestamp, endcreatetimestamp, simulate);
            //Assert.IsType<OrderDetailResponse>(response);
        }

        /// <summary>
        /// Test PostV5OrdersCreate
        /// </summary>
        [Fact]
        public void PostV5OrdersCreateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderCreateRequest? orderCreateRequest = null;
            //var response = instance.PostV5OrdersCreate(orderCreateRequest);
            //Assert.IsType<OrderCreateResponse>(response);
        }
    }
}
