/*
 * Reseller API Documentation
 *
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using xi.sdk.resellers.csharp.Client;
using xi.sdk.resellers.csharp.Api;
// uncomment below to import models
//using xi.sdk.resellers.csharp.Model;

namespace xi.sdk.resellers.csharp.Test.Api
{
    /// <summary>
    ///  Class for testing OrdersV6Api
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class OrdersV6ApiTests : IDisposable
    {
        private OrdersV6Api instance;

        public OrdersV6ApiTests()
        {
            instance = new OrdersV6Api();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrdersV6Api
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' OrdersV6Api
            //Assert.IsType<OrdersV6Api>(instance);
        }

        /// <summary>
        /// Test GetOrderdetailsV6
        /// </summary>
        [Fact]
        public void GetOrderdetailsV6Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string ordernumber = null;
            //string iMCustomerNumber = null;
            //string iMCountryCode = null;
            //string iMCorrelationID = null;
            //string? iMSenderID = null;
            //DateTime? ingramOrderDate = null;
            //string? vendorNumber = null;
            //string? simulateStatus = null;
            //bool? isIml = null;
            //string? regionCode = null;
            //var response = instance.GetOrderdetailsV6(ordernumber, iMCustomerNumber, iMCountryCode, iMCorrelationID, iMSenderID, ingramOrderDate, vendorNumber, simulateStatus, isIml, regionCode);
            //Assert.IsType<OrderDetailResponse>(response);
        }
    }
}
