/*
 * Reseller API Documentation
 *
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = xi.sdk.resellers.csharp.Client.FileParameter;
using OpenAPIDateConverter = xi.sdk.resellers.csharp.Client.OpenAPIDateConverter;

namespace xi.sdk.resellers.csharp.Model
{
    /// <summary>
    /// The shipment carrier details for the line item.
    /// </summary>
    [DataContract(Name = "OrderDetailResponse_lines_inner_shipmentDetails_inner_carrierDetails")]
    public partial class OrderDetailResponseLinesInnerShipmentDetailsInnerCarrierDetails : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderDetailResponseLinesInnerShipmentDetailsInnerCarrierDetails" /> class.
        /// </summary>
        /// <param name="carrierCode">The carrier code for the shipment containing the line item..</param>
        /// <param name="carrierName">The name of the carrier of the shipment containing the line item..</param>
        /// <param name="trackingDetails">trackingDetails.</param>
        public OrderDetailResponseLinesInnerShipmentDetailsInnerCarrierDetails(string carrierCode = default(string), string carrierName = default(string), List<OrderDetailResponseLinesInnerShipmentDetailsInnerCarrierDetailsTrackingDetailsInner> trackingDetails = default(List<OrderDetailResponseLinesInnerShipmentDetailsInnerCarrierDetailsTrackingDetailsInner>))
        {
            this.CarrierCode = carrierCode;
            this.CarrierName = carrierName;
            this.TrackingDetails = trackingDetails;
        }

        /// <summary>
        /// The carrier code for the shipment containing the line item.
        /// </summary>
        /// <value>The carrier code for the shipment containing the line item.</value>
        [DataMember(Name = "carrierCode", EmitDefaultValue = false)]
        public string CarrierCode { get; set; }

        /// <summary>
        /// The name of the carrier of the shipment containing the line item.
        /// </summary>
        /// <value>The name of the carrier of the shipment containing the line item.</value>
        [DataMember(Name = "carrierName", EmitDefaultValue = false)]
        public string CarrierName { get; set; }

        /// <summary>
        /// Gets or Sets TrackingDetails
        /// </summary>
        [DataMember(Name = "trackingDetails", EmitDefaultValue = false)]
        public List<OrderDetailResponseLinesInnerShipmentDetailsInnerCarrierDetailsTrackingDetailsInner> TrackingDetails { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrderDetailResponseLinesInnerShipmentDetailsInnerCarrierDetails {\n");
            sb.Append("  CarrierCode: ").Append(CarrierCode).Append("\n");
            sb.Append("  CarrierName: ").Append(CarrierName).Append("\n");
            sb.Append("  TrackingDetails: ").Append(TrackingDetails).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
