/*
 * Reseller API Documentation - United States
 *
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi-sdk-csharp.Model;
using xi-sdk-csharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi-sdk-csharp.Test.Model
{
    /// <summary>
    ///  Class for testing InvoiceDetailsv61ResponseSummaryTotals
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InvoiceDetailsv61ResponseSummaryTotalsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InvoiceDetailsv61ResponseSummaryTotals
        //private InvoiceDetailsv61ResponseSummaryTotals instance;

        public InvoiceDetailsv61ResponseSummaryTotalsTests()
        {
            // TODO uncomment below to create an instance of InvoiceDetailsv61ResponseSummaryTotals
            //instance = new InvoiceDetailsv61ResponseSummaryTotals();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InvoiceDetailsv61ResponseSummaryTotals
        /// </summary>
        [Fact]
        public void InvoiceDetailsv61ResponseSummaryTotalsInstanceTest()
        {
            // TODO uncomment below to test "IsType" InvoiceDetailsv61ResponseSummaryTotals
            //Assert.IsType<InvoiceDetailsv61ResponseSummaryTotals>(instance);
        }

        /// <summary>
        /// Test the property 'NetInvoiceAmount'
        /// </summary>
        [Fact]
        public void NetInvoiceAmountTest()
        {
            // TODO unit test for the property 'NetInvoiceAmount'
        }

        /// <summary>
        /// Test the property 'DiscountAmount'
        /// </summary>
        [Fact]
        public void DiscountAmountTest()
        {
            // TODO unit test for the property 'DiscountAmount'
        }

        /// <summary>
        /// Test the property 'DiscountType'
        /// </summary>
        [Fact]
        public void DiscountTypeTest()
        {
            // TODO unit test for the property 'DiscountType'
        }

        /// <summary>
        /// Test the property 'TotalTaxAmount'
        /// </summary>
        [Fact]
        public void TotalTaxAmountTest()
        {
            // TODO unit test for the property 'TotalTaxAmount'
        }

        /// <summary>
        /// Test the property 'InvoicedAmountDue'
        /// </summary>
        [Fact]
        public void InvoicedAmountDueTest()
        {
            // TODO unit test for the property 'InvoicedAmountDue'
        }

        /// <summary>
        /// Test the property 'FreightAmount'
        /// </summary>
        [Fact]
        public void FreightAmountTest()
        {
            // TODO unit test for the property 'FreightAmount'
        }
    }
}
