/*
 * Reseller API Documentation - United States
 *
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi-sdk-csharp.Model;
using xi-sdk-csharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi-sdk-csharp.Test.Model
{
    /// <summary>
    ///  Class for testing OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerEnduser
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerEnduserTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerEnduser
        //private OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerEnduser instance;

        public OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerEnduserTests()
        {
            // TODO uncomment below to create an instance of OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerEnduser
            //instance = new OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerEnduser();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerEnduser
        /// </summary>
        [Fact]
        public void OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerEnduserInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerEnduser
            //Assert.IsType<OrderCreateRequestOrdercreaterequestOrdercreatedetailsLinesInnerEnduser>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Addressline1'
        /// </summary>
        [Fact]
        public void Addressline1Test()
        {
            // TODO unit test for the property 'Addressline1'
        }

        /// <summary>
        /// Test the property 'Addressline2'
        /// </summary>
        [Fact]
        public void Addressline2Test()
        {
            // TODO unit test for the property 'Addressline2'
        }

        /// <summary>
        /// Test the property 'Addressline3'
        /// </summary>
        [Fact]
        public void Addressline3Test()
        {
            // TODO unit test for the property 'Addressline3'
        }

        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'Postalcode'
        /// </summary>
        [Fact]
        public void PostalcodeTest()
        {
            // TODO unit test for the property 'Postalcode'
        }

        /// <summary>
        /// Test the property 'Countrycode'
        /// </summary>
        [Fact]
        public void CountrycodeTest()
        {
            // TODO unit test for the property 'Countrycode'
        }

        /// <summary>
        /// Test the property 'Phonenumber'
        /// </summary>
        [Fact]
        public void PhonenumberTest()
        {
            // TODO unit test for the property 'Phonenumber'
        }

        /// <summary>
        /// Test the property 'Extensionnumber'
        /// </summary>
        [Fact]
        public void ExtensionnumberTest()
        {
            // TODO unit test for the property 'Extensionnumber'
        }

        /// <summary>
        /// Test the property 'Faxnumber'
        /// </summary>
        [Fact]
        public void FaxnumberTest()
        {
            // TODO unit test for the property 'Faxnumber'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
    }
}
