/*
 * Reseller API Documentation - United States
 *
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi-sdk-csharp.Model;
using xi-sdk-csharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi-sdk-csharp.Test.Model
{
    /// <summary>
    ///  Class for testing OrderCreateRequestOrdercreaterequestOrdercreatedetailsShiptoaddress
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderCreateRequestOrdercreaterequestOrdercreatedetailsShiptoaddressTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderCreateRequestOrdercreaterequestOrdercreatedetailsShiptoaddress
        //private OrderCreateRequestOrdercreaterequestOrdercreatedetailsShiptoaddress instance;

        public OrderCreateRequestOrdercreaterequestOrdercreatedetailsShiptoaddressTests()
        {
            // TODO uncomment below to create an instance of OrderCreateRequestOrdercreaterequestOrdercreatedetailsShiptoaddress
            //instance = new OrderCreateRequestOrdercreaterequestOrdercreatedetailsShiptoaddress();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderCreateRequestOrdercreaterequestOrdercreatedetailsShiptoaddress
        /// </summary>
        [Fact]
        public void OrderCreateRequestOrdercreaterequestOrdercreatedetailsShiptoaddressInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderCreateRequestOrdercreaterequestOrdercreatedetailsShiptoaddress
            //Assert.IsType<OrderCreateRequestOrdercreaterequestOrdercreatedetailsShiptoaddress>(instance);
        }

        /// <summary>
        /// Test the property 'Attention'
        /// </summary>
        [Fact]
        public void AttentionTest()
        {
            // TODO unit test for the property 'Attention'
        }

        /// <summary>
        /// Test the property 'Addressline1'
        /// </summary>
        [Fact]
        public void Addressline1Test()
        {
            // TODO unit test for the property 'Addressline1'
        }

        /// <summary>
        /// Test the property 'Addressline2'
        /// </summary>
        [Fact]
        public void Addressline2Test()
        {
            // TODO unit test for the property 'Addressline2'
        }

        /// <summary>
        /// Test the property 'Addressline3'
        /// </summary>
        [Fact]
        public void Addressline3Test()
        {
            // TODO unit test for the property 'Addressline3'
        }

        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'Postalcode'
        /// </summary>
        [Fact]
        public void PostalcodeTest()
        {
            // TODO unit test for the property 'Postalcode'
        }

        /// <summary>
        /// Test the property 'Countrycode'
        /// </summary>
        [Fact]
        public void CountrycodeTest()
        {
            // TODO unit test for the property 'Countrycode'
        }
    }
}
