/*
 * Reseller API Documentation - United States
 *
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi-sdk-csharp.Model;
using xi-sdk-csharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi-sdk-csharp.Test.Model
{
    /// <summary>
    ///  Class for testing PriceAndAvailabilityResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PriceAndAvailabilityResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PriceAndAvailabilityResponse
        //private PriceAndAvailabilityResponse instance;

        public PriceAndAvailabilityResponseTests()
        {
            // TODO uncomment below to create an instance of PriceAndAvailabilityResponse
            //instance = new PriceAndAvailabilityResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PriceAndAvailabilityResponse
        /// </summary>
        [Fact]
        public void PriceAndAvailabilityResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PriceAndAvailabilityResponse
            //Assert.IsType<PriceAndAvailabilityResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Serviceresponse'
        /// </summary>
        [Fact]
        public void ServiceresponseTest()
        {
            // TODO unit test for the property 'Serviceresponse'
        }
    }
}
