/*
 * Reseller API Documentation
 *
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using xi-sdk-resellers-csharp.Client;
using xi-sdk-resellers-csharp.Api;
// uncomment below to import models
//using xi-sdk-resellers-csharp.Model;

namespace xi-sdk-resellers-csharp.Test.Api
{
    /// <summary>
    ///  Class for testing InvoicesV6Api
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class InvoicesV6ApiTests : IDisposable
    {
        private InvoicesV6Api instance;

        public InvoicesV6ApiTests()
        {
            instance = new InvoicesV6Api();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InvoicesV6Api
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' InvoicesV6Api
            //Assert.IsType<InvoicesV6Api>(instance);
        }

        /// <summary>
        /// Test GetInvoicedetailsV6
        /// </summary>
        [Fact]
        public void GetInvoicedetailsV6Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string invoicenumber = null;
            //string varVersion = null;
            //string iMCustomerNumber = null;
            //string iMCountryCode = null;
            //string iMCorrelationID = null;
            //string iMApplicationID = null;
            //string? customerType = null;
            //bool? includeSerialNumbers = null;
            //var response = instance.GetInvoicedetailsV6(invoicenumber, varVersion, iMCustomerNumber, iMCountryCode, iMCorrelationID, iMApplicationID, customerType, includeSerialNumbers);
            //Assert.IsType<InvoiceDetailResponse>(response);
        }
    }
}
