/*
 * Reseller API Documentation - United States
 *
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = xi-sdk-csharp.Client.OpenAPIDateConverter;

namespace xi-sdk-csharp.Model
{
    /// <summary>
    /// ProductLineTypeSerialnumberdetailsInner
    /// </summary>
    [DataContract(Name = "productLineType_serialnumberdetails_inner")]
    public partial class ProductLineTypeSerialnumberdetailsInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductLineTypeSerialnumberdetailsInner" /> class.
        /// </summary>
        /// <param name="serialnumber">serialnumber.</param>
        /// <param name="deliverynumber">deliverynumber.</param>
        public ProductLineTypeSerialnumberdetailsInner(string serialnumber = default(string), string deliverynumber = default(string))
        {
            this.Serialnumber = serialnumber;
            this.Deliverynumber = deliverynumber;
        }

        /// <summary>
        /// Gets or Sets Serialnumber
        /// </summary>
        [DataMember(Name = "serialnumber", EmitDefaultValue = false)]
        public string Serialnumber { get; set; }

        /// <summary>
        /// Gets or Sets Deliverynumber
        /// </summary>
        [DataMember(Name = "deliverynumber", EmitDefaultValue = false)]
        public string Deliverynumber { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProductLineTypeSerialnumberdetailsInner {\n");
            sb.Append("  Serialnumber: ").Append(Serialnumber).Append("\n");
            sb.Append("  Deliverynumber: ").Append(Deliverynumber).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
