/*
 * Reseller API
 *
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = xi.sdk.resellers.Client.FileParameter;
using OpenAPIDateConverter = xi.sdk.resellers.Client.OpenAPIDateConverter;

namespace xi.sdk.resellers.Model
{
    /// <summary>
    /// OrderDeleteRequestServicerequest
    /// </summary>
    [DataContract(Name = "orderDeleteRequest_servicerequest")]
    public partial class OrderDeleteRequestServicerequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderDeleteRequestServicerequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected OrderDeleteRequestServicerequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderDeleteRequestServicerequest" /> class.
        /// </summary>
        /// <param name="requestpreamble">requestpreamble (required).</param>
        /// <param name="orderDeleteRequestDetails">orderDeleteRequestDetails.</param>
        public OrderDeleteRequestServicerequest(OrderDeleteRequestServicerequestRequestpreamble requestpreamble = default(OrderDeleteRequestServicerequestRequestpreamble), OrderDeleteRequestServicerequestOrderDeleteRequestDetails orderDeleteRequestDetails = default(OrderDeleteRequestServicerequestOrderDeleteRequestDetails))
        {
            // to ensure "requestpreamble" is required (not null)
            if (requestpreamble == null)
            {
                throw new ArgumentNullException("requestpreamble is a required property for OrderDeleteRequestServicerequest and cannot be null");
            }
            this.Requestpreamble = requestpreamble;
            this.OrderDeleteRequestDetails = orderDeleteRequestDetails;
        }

        /// <summary>
        /// Gets or Sets Requestpreamble
        /// </summary>
        [DataMember(Name = "requestpreamble", IsRequired = true, EmitDefaultValue = true)]
        public OrderDeleteRequestServicerequestRequestpreamble Requestpreamble { get; set; }

        /// <summary>
        /// Gets or Sets OrderDeleteRequestDetails
        /// </summary>
        [DataMember(Name = "OrderDeleteRequestDetails", EmitDefaultValue = false)]
        public OrderDeleteRequestServicerequestOrderDeleteRequestDetails OrderDeleteRequestDetails { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrderDeleteRequestServicerequest {\n");
            sb.Append("  Requestpreamble: ").Append(Requestpreamble).Append("\n");
            sb.Append("  OrderDeleteRequestDetails: ").Append(OrderDeleteRequestDetails).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
