/*
 * Reseller API Documentation
 *
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi-sdk-resellers-csharp.Model;
using xi-sdk-resellers-csharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi-sdk-resellers-csharp.Test.Model
{
    /// <summary>
    ///  Class for testing OrderSearchRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderSearchRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderSearchRequest
        //private OrderSearchRequest instance;

        public OrderSearchRequestTests()
        {
            // TODO uncomment below to create an instance of OrderSearchRequest
            //instance = new OrderSearchRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderSearchRequest
        /// </summary>
        [Fact]
        public void OrderSearchRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderSearchRequest
            //Assert.IsType<OrderSearchRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Servicerequest'
        /// </summary>
        [Fact]
        public void ServicerequestTest()
        {
            // TODO unit test for the property 'Servicerequest'
        }
    }
}
