/*
 * Reseller API Documentation
 *
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi-sdk-resellers-csharp.Model;
using xi-sdk-resellers-csharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi-sdk-resellers-csharp.Test.Model
{
    /// <summary>
    ///  Class for testing OrderDetailResponseServiceresponseOrderdetailresponseLinesInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderDetailResponseServiceresponseOrderdetailresponseLinesInner
        //private OrderDetailResponseServiceresponseOrderdetailresponseLinesInner instance;

        public OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerTests()
        {
            // TODO uncomment below to create an instance of OrderDetailResponseServiceresponseOrderdetailresponseLinesInner
            //instance = new OrderDetailResponseServiceresponseOrderdetailresponseLinesInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderDetailResponseServiceresponseOrderdetailresponseLinesInner
        /// </summary>
        [Fact]
        public void OrderDetailResponseServiceresponseOrderdetailresponseLinesInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderDetailResponseServiceresponseOrderdetailresponseLinesInner
            //Assert.IsType<OrderDetailResponseServiceresponseOrderdetailresponseLinesInner>(instance);
        }

        /// <summary>
        /// Test the property 'Linenumber'
        /// </summary>
        [Fact]
        public void LinenumberTest()
        {
            // TODO unit test for the property 'Linenumber'
        }

        /// <summary>
        /// Test the property 'Globallinenumber'
        /// </summary>
        [Fact]
        public void GloballinenumberTest()
        {
            // TODO unit test for the property 'Globallinenumber'
        }

        /// <summary>
        /// Test the property 'Ordersuffix'
        /// </summary>
        [Fact]
        public void OrdersuffixTest()
        {
            // TODO unit test for the property 'Ordersuffix'
        }

        /// <summary>
        /// Test the property 'Erpordernumber'
        /// </summary>
        [Fact]
        public void ErpordernumberTest()
        {
            // TODO unit test for the property 'Erpordernumber'
        }

        /// <summary>
        /// Test the property 'Linestatus'
        /// </summary>
        [Fact]
        public void LinestatusTest()
        {
            // TODO unit test for the property 'Linestatus'
        }

        /// <summary>
        /// Test the property 'Partnumber'
        /// </summary>
        [Fact]
        public void PartnumberTest()
        {
            // TODO unit test for the property 'Partnumber'
        }

        /// <summary>
        /// Test the property 'Manufacturerpartnumber'
        /// </summary>
        [Fact]
        public void ManufacturerpartnumberTest()
        {
            // TODO unit test for the property 'Manufacturerpartnumber'
        }

        /// <summary>
        /// Test the property 'Vendorname'
        /// </summary>
        [Fact]
        public void VendornameTest()
        {
            // TODO unit test for the property 'Vendorname'
        }

        /// <summary>
        /// Test the property 'Vendorcode'
        /// </summary>
        [Fact]
        public void VendorcodeTest()
        {
            // TODO unit test for the property 'Vendorcode'
        }

        /// <summary>
        /// Test the property 'Partdescription1'
        /// </summary>
        [Fact]
        public void Partdescription1Test()
        {
            // TODO unit test for the property 'Partdescription1'
        }

        /// <summary>
        /// Test the property 'Partdescription2'
        /// </summary>
        [Fact]
        public void Partdescription2Test()
        {
            // TODO unit test for the property 'Partdescription2'
        }

        /// <summary>
        /// Test the property 'Unitweight'
        /// </summary>
        [Fact]
        public void UnitweightTest()
        {
            // TODO unit test for the property 'Unitweight'
        }

        /// <summary>
        /// Test the property 'Unitprice'
        /// </summary>
        [Fact]
        public void UnitpriceTest()
        {
            // TODO unit test for the property 'Unitprice'
        }

        /// <summary>
        /// Test the property 'Extendedprice'
        /// </summary>
        [Fact]
        public void ExtendedpriceTest()
        {
            // TODO unit test for the property 'Extendedprice'
        }

        /// <summary>
        /// Test the property 'Taxamount'
        /// </summary>
        [Fact]
        public void TaxamountTest()
        {
            // TODO unit test for the property 'Taxamount'
        }

        /// <summary>
        /// Test the property 'Requestedquantity'
        /// </summary>
        [Fact]
        public void RequestedquantityTest()
        {
            // TODO unit test for the property 'Requestedquantity'
        }

        /// <summary>
        /// Test the property 'Confirmedquantity'
        /// </summary>
        [Fact]
        public void ConfirmedquantityTest()
        {
            // TODO unit test for the property 'Confirmedquantity'
        }

        /// <summary>
        /// Test the property 'Backorderquantity'
        /// </summary>
        [Fact]
        public void BackorderquantityTest()
        {
            // TODO unit test for the property 'Backorderquantity'
        }

        /// <summary>
        /// Test the property 'Serialnumberdetails'
        /// </summary>
        [Fact]
        public void SerialnumberdetailsTest()
        {
            // TODO unit test for the property 'Serialnumberdetails'
        }

        /// <summary>
        /// Test the property 'Trackingnumber'
        /// </summary>
        [Fact]
        public void TrackingnumberTest()
        {
            // TODO unit test for the property 'Trackingnumber'
        }

        /// <summary>
        /// Test the property 'Shipmentdetails'
        /// </summary>
        [Fact]
        public void ShipmentdetailsTest()
        {
            // TODO unit test for the property 'Shipmentdetails'
        }

        /// <summary>
        /// Test the property 'Productextendedspecs'
        /// </summary>
        [Fact]
        public void ProductextendedspecsTest()
        {
            // TODO unit test for the property 'Productextendedspecs'
        }

        /// <summary>
        /// Test the property 'Backorderetadate'
        /// </summary>
        [Fact]
        public void BackorderetadateTest()
        {
            // TODO unit test for the property 'Backorderetadate'
        }
    }
}
