/*
 * Reseller API Documentation
 *
 * For Resellers. <br> Who are looking to Innovate with Ingram Micro's API SolutionsAutomate your eCommerce with our offering of APIs and Webhooks to create a seamless experience for your customers.
 *
 * The version of the OpenAPI document: 6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi-sdk-resellers-csharp.Model;
using xi-sdk-resellers-csharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi-sdk-resellers-csharp.Test.Model
{
    /// <summary>
    ///  Class for testing QuoteListRequestQuoteSearchRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class QuoteListRequestQuoteSearchRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for QuoteListRequestQuoteSearchRequest
        //private QuoteListRequestQuoteSearchRequest instance;

        public QuoteListRequestQuoteSearchRequestTests()
        {
            // TODO uncomment below to create an instance of QuoteListRequestQuoteSearchRequest
            //instance = new QuoteListRequestQuoteSearchRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of QuoteListRequestQuoteSearchRequest
        /// </summary>
        [Fact]
        public void QuoteListRequestQuoteSearchRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" QuoteListRequestQuoteSearchRequest
            //Assert.IsType<QuoteListRequestQuoteSearchRequest>(instance);
        }

        /// <summary>
        /// Test the property 'RequestPreamble'
        /// </summary>
        [Fact]
        public void RequestPreambleTest()
        {
            // TODO unit test for the property 'RequestPreamble'
        }

        /// <summary>
        /// Test the property 'RetrieveQuoteRequest'
        /// </summary>
        [Fact]
        public void RetrieveQuoteRequestTest()
        {
            // TODO unit test for the property 'RetrieveQuoteRequest'
        }
    }
}
